name: Sync Github Repos To Gitee

on:
  push:
    branches: [main]
    paths:
      - 'public/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
#     - name: Minio Deploy
#       uses: mamal72/minio-perfect-deploy-action@main
#       with:
#         endpoint: ${{ secrets.MINIO_ENDPOINT }}
#         access_key: ${{ secrets.MINIO_ACCESS_KEY }}
#         secret_key: ${{ secrets.MINIO_SECRET_KEY }}
#         bucket: 'public'
#         source_dir: 'public/'
#         target_dir: '/'
    - name: Minio Deploy
      uses: mamal72/minio-perfect-deploy-action@main
      env:
        endpoint: ${{ secrets.MINIO_ENDPOINT }}
        access_key: ${{ secrets.MINIO_ACCESS_KEY }}
        secret_key: ${{ secrets.MINIO_SECRET_KEY }}
        bucket: ${{ secrets.MINIO_BUCKET }}
        source_dir: 'public'
        target_dir: '/'
    - run: |
        ls public/images
        mc alias set pi-minio $endpoint $access_key $secret_key
        mc alias ls
        mc mirror $source_dir pi-minio/$bucket$target_dir --remove --overwrite
        
    - name: Sync Github Repos To Gitee  # 名字随便起
      uses: Yikun/hub-mirror-action@master  # 使用Yikun/hub-mirror-action
      with:
        src: github/weizj2000  # 源端账户名(github)
        dst: gitee/weizj2000  # 目的端账户名(gitee)
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}  # SSH密钥对中的私钥
        dst_token:  ${{ secrets.GITEE_TOKEN }}  # Gitee账户的私人令牌
        account_type: user  # 账户类型
        clone_style: "ssh"  # 使用https方式进行clone，也可以使用ssh
        debug: true  # 启用后会显示所有执行命令
        force_update: true  # 启用后，强制同步，即强制覆盖目的端仓库
        static_list: "resource"  # 静态同步列表，在此填写需要同步的仓库名称，可填写多个
        timeout: '600s'  # git超时设置，超时后会自动重试git操作
        cache_path: /repo-cache
